name: Parse print request

on:
  issues:
    types: [opened, edited]

concurrency: 'main'

permissions:
  issues: write

jobs:
  parse-and-comment:
    if: contains(github.event.issue.labels.*.name, 'print-request')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/print-request.yml
    
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > order.json

      - run: cat order.json

      - run: gh issue comment {{ github.event.issue.number }} --body "This is a test!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
