name: Parse print request

on:
  issues:
    types: [opened, edited]

concurrency: 'main'

permissions:
  issues: write

jobs:
  parse-and-comment:
    if: contains(github.event.issue.labels.*.name, 'print-request')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          node-version-file: '3d-print/package.json'

      - name: Install packages
        run: sudo apt install python3 curl unzip jq prusa-slicer -y

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/print-request.yml
    
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > request.json

      - run: cat request.json

      - run: python 3d-print/gcode-make.py
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
          PROJECT_NUMBER: 3

      - run: gh issue comment ${{ github.event.issue.number }} --body-file comment 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
